<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="10503-2F-FB0V6T2" name="Default test" tests="6" failures="1" timestamp="15 Oct 2019 11:12:54 GMT" time="270.157" errors="0">
  <testcase name="loginTest1" time="0.313" classname="com.cm.testscripts.LoginTest2">
    <failure type="java.io.FileNotFoundException" message=".CBSIOS_3.1\Resources\IOS_LoginTestdata.xls (The system cannot find the path specified)">
      <![CDATA[java.io.FileNotFoundException: .CBSIOS_3.1\Resources\IOS_LoginTestdata.xls (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.cm.Utility.ExcelData.getExcelData(ExcelData.java:20)
	at com.cm.testscripts.LoginTest2.loginTest1(LoginTest2.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginTest1 -->
  <testcase name="loginTest2" time="28.995" classname="com.cm.testscripts.LoginTest2"/>
  <testcase name="loginTest3" time="84.787" classname="com.cm.testscripts.LoginTest2"/>
  <testcase name="loginTest4" time="34.146" classname="com.cm.testscripts.LoginTest2"/>
  <testcase name="loginTest5" time="48.949" classname="com.cm.testscripts.LoginTest2"/>
  <testcase name="loginTest6" time="38.267" classname="com.cm.testscripts.LoginTest2"/>
</testsuite> <!-- Default test -->
